### PR TITLE
Getting this Repo up-to-date.

### PR DESCRIPTION
**Pull request by Tannoo**

### CODE REVIEW

**Comment by Tannoo** [comment]
I had also cleaned up the comments in `configuration.h` and `configuration_adv.h`.

**Comment by ruggb** [comment]
I will post my new configs soon. Be interested to compare notes. Though it sounds like what you did was just about the comments. There are a couple of comments about variable that need work as I can't figure out what the variable do from the comments. I only have maybe 2 items in the adv file. That is because they are affected by load sequence and if I put them in the config file it doesn't compile. Everything else is in the config file and there is only one section for extruder, temperature, motion, lcd, etc. MUCH less confusing IMHO.

**Comment by Tannoo** [comment]
Ok. I am interested to see what you've got.

Yes, I was working with the comments as a first step in what you were proposing in another discussion.

**Comment by ruggb** [comment]
The biggest thing about the comments is using /*......*/ for single lines - /**, *, */ for multilines and only use // at the end of a code line. That is to help make a commented out code line more visible.
Obviously, or maybe not, there are many comments/instructions that can be improved.

**Comment by Tannoo** [comment]
I was trying to implement it as 

/* comment */

And

/*
 * comment
 * some more
 */

To be consistant.

**Comment by ruggb** [comment]
ye for some reason the * didn't appear in my last. Placing the close */ indented is better for seeing a commented out code line but will probably become inconsistent in a heartbeat.
// for end of line comments

**Pull request closed without merging**
